1. always test your stuff before running it. especially if running it makes it a lot slower with a larger input size.  exmaple: the time i wasted writing the whole thing to a file. I thought it would just work, I should have tested it on a slice col_names, write to file (to make sure it was writing correctly and that i was using the syntax correctly), then executed it on the whole thing.
2. empathy, no need to be condescending
